global:
  application_name: game-scoreboard
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  profile: eb-cli
  workspace_type: Application



  # to run it : eb init & eb create game-score-env & eb deploy
